config/routes.rb
Rails.application.routes.draw do
  authenticated do
    root 'rooms#index', as: :authenticated_root
  end

  devise_scope :user do
    root "users/sessions#new"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  resources :rooms do
    resources :messages
  end

  resources :search_messages, only: %i[index]

  get 'home' => 'home#index'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/search_messages_controller.rb
class SearchMessagesController < ApplicationController
  def index
    @search_messages_form = SearchMessagesForm.new(message_params)
    @messages = @search_messages_form.search
  end

  private

  def message_params
    params[:q]&.permit(:body)
  end
end

app/views/search_messages/_form.html.slim
= simple_form_for(search_messages_form, as: :q, url: search_messages_path, method: :get) do |f|
  = f.input :body, as: :text
  = f.button :submit

app/views/search_messages/index.html.slim
h1 SearchMessages#index
p Find me in app/views/search_messages/index.html.slim
= render 'form', search_messages_form: @search_messages_form

#text_messages
  = render partial: 'messages/message', collection: @messages