config/routes.rb
Rails.application.routes.draw do
  authenticated do
    root 'rooms#index', as: :authenticated_root
  end

  devise_scope :user do
    root "users/sessions#new"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  resources :rooms do
    resources :messages
  end

  resources :search_messages, only: %i[index]

  get 'home' => 'home#index'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms
  def index
    @rooms = Room.all
    @search_messages_form = SearchMessagesForm.new
  end

  # GET /rooms/1
  def show
    @message = Message.new
    @messages = @room.messages
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to rooms_path, notice: "チャットを作成しました"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /rooms/1
  def update
    if @room.update(room_params)
      redirect_to @room, notice: "Room was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /rooms/1
  def destroy
    @room.destroy!
    redirect_to rooms_url, notice: "Room was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/views/rooms/_form.html.slim
= simple_form_for(room) do |f|
  = f.input :name
  = f.button :submit

app/views/rooms/_room.html.slim
div id="#{dom_id room}"
  p
    strong Name:
    =< room.name

app/views/rooms/edit.html.slim
h1 Editing room

== render "form", room: @room

br

div
  => link_to "Show this room", @room
  '|
  =< link_to "Back to rooms", rooms_path

app/views/rooms/index.html.slim
p style="color: green" = notice

p Search messages
= render 'search_messages/form', search_messages_form: @search_messages_form

h1 Rooms

#rooms
  - @rooms.each do |room|
    == render room
    p
      = link_to "Show this room", room

= link_to "New room", new_room_path

app/views/rooms/new.html.slim
h1 New room

== render "form", room: @room

br

div
  = link_to "Back to rooms", rooms_path

app/views/rooms/show.html.slim
p style="color: green" = notice

= @room.name

= turbo_stream_from @room
#text_messages
  = render partial: 'messages/message', collection: @messages

div id="message_form_#{@room.id}"
  = render 'messages/form', message: @message, room: @room

div
  = link_to "チャット一覧に戻る", rooms_path